// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkBHN7jThiuvs8OU1oYrEbDaG3RmsYwBU',
    appId: '1:595698570313:web:9e051dd4a86704dd335b98',
    messagingSenderId: '595698570313',
    projectId: 'aplikasi-tv-masjid',
    authDomain: 'aplikasi-tv-masjid.firebaseapp.com',
    storageBucket: 'aplikasi-tv-masjid.appspot.com',
    measurementId: 'G-ESPX4FKT58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTHuqa2fiy2ELUyLRSjFGr-XqC5MYI8i0',
    appId: '1:595698570313:android:cde6267840ced5fd335b98',
    messagingSenderId: '595698570313',
    projectId: 'aplikasi-tv-masjid',
    storageBucket: 'aplikasi-tv-masjid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEfzQwBcZCT8EG40-GJgTSHdMrzjr0LR8',
    appId: '1:595698570313:ios:cf33a184be285815335b98',
    messagingSenderId: '595698570313',
    projectId: 'aplikasi-tv-masjid',
    storageBucket: 'aplikasi-tv-masjid.appspot.com',
    iosClientId: '595698570313-onp0f3p7ehams1boom7uhpu0v604qkt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.masterMasjid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEfzQwBcZCT8EG40-GJgTSHdMrzjr0LR8',
    appId: '1:595698570313:ios:cf33a184be285815335b98',
    messagingSenderId: '595698570313',
    projectId: 'aplikasi-tv-masjid',
    storageBucket: 'aplikasi-tv-masjid.appspot.com',
    iosClientId: '595698570313-onp0f3p7ehams1boom7uhpu0v604qkt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.masterMasjid',
  );
}
